
SELECT

    dp.category,

    -- Number of sales transactions (order-product combinations)

    COUNT(*) AS total_order_lines,


    SUM(fs.quantity_sold) AS total_quantity_sold,

    -- Revenue generated from the category

    ROUND(
        SUM(fs.total_sales_amount),
        2
    ) AS total_sales_amount,

    -- Total profit generated by the category

    ROUND(
        SUM(fs.profit_amount),
        2
    ) AS total_profit_amount

FROM {{ ref('fact_sales') }} fs

    -- Join Product Dimension to access category information

    INNER JOIN {{ ref('dim_product') }} dp
        ON fs.product_key = dp.product_key

-- Aggregate metrics at Product Category level

GROUP BY
    dp.category

-- Show highest revenue-generating categories first

ORDER BY
    total_sales_amount DESC